name: PR

on: pull_request

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: read

jobs:
  superlinter:
    name: Lint bash, markdown, and yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Lint codebase
        uses: docker://github/super-linter:v3.8.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_MD: true
          VALIDATE_YAML: true

  verify-changelog:
    name: Verify CHANGELOG is valid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Verify CHANGELOG
        uses: docker://ghcr.io/ponylang/changelog-tool:release
        with:
          args: changelog-tool verify

  test-openssl-3-vs-ponyc-release:
    name: OpenSSL 3.x with most recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/shared-docker-ci-standard-builder-with-openssl-3.6.0:release
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Test
        run: make test config=debug ssl=3.0.x

  test-openssl-1-vs-ponyc-release:
    name: OpenSSL 1.x with most recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-openssl_1.1.1w:release
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Test
        run: make test config=debug ssl=1.1.x

  test-libressl-3-vs-ponyc-release:
    name: LibreSSL 3.x with most recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-libressl-3.9.2:release
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Test
        run: make test config=debug ssl=libressl

  test-libressl-4-vs-ponyc-release:
    name: LibreSSL 4.x with most recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/shared-docker-ci-standard-builder-with-libressl-4.2.0:release
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Test
        run: make test config=debug ssl=libressl
